
spring:
  application:
    name: carrepository
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    instanceId: ${spring.application.name}:${random.value}
management:
  endpoints:
    web:
      exposure:
        include: prometheus

okta:
  oauth2:
    issuer: https://dev-5ga4j08xhdasu7gq.us.auth0.com
    audience: https://dev-5ga4j08xhdasu7gq.us.auth0.com/api/v2/