server:
  port: 8060

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      mvc:
        routes:
          - id: carrepository-metrics
            uri: lb://carrepository
            predicates:
              - Path=/microservice/1.0.0./carrepository/actuator/prometheus
            filters:
              - RewritePath=/microservice/1.0.0./carrepository/actuator/prometheus, /actuator/prometheus
          - id: carrepository
            uri: lb://carrepository
            predicates:
              - Path=/microservice/1.0.0./carrepository/**
          - id: customerservice-metrics
            uri: lb://customerservice
            predicates:
              - Path=/microservice/1.0.0./customers/actuator/prometheus
            filters:
              - RewritePath=/microservice/1.0.0./customers/actuator/prometheus, /actuator/prometheus
          - id: customerservice
            uri: lb://customerservice
            predicates:
              - Path=/microservice/1.0.0./customers/**
          - id: bookingservice-metrics
            uri: lb://boookingservice
            predicates:
              - Path=/microservice/1.0.0./booking/actuator/prometheus
            filters:
              - RewritePath=/microservice/1.0.0./booking/actuator/prometheus, /actuator/prometheus
          - id: bookingservice
            uri: lb://boookingservice
            predicates:
              - Path=/microservice/1.0.0./booking/**
          - id: paymentservice-metrics
            uri: lb://paymentservice
            predicates:
              - Path=/microservices/1.0.0./payment/actuator/prometheus
            filters:
              - RewritePath=/microservices/1.0.0./payment/actuator/prometheus, /actuator/prometheus
          - id: paymentservice
            uri: lb://paymentservice
            predicates:
              - Path=/microservices/1.0.0./payment/**
okta:
  oauth2:
    issuer: https://dev-5ga4j08xhdasu7gq.us.auth0.com/
    client-id: 3GzxBviz5U92qV12Ftszh4Heju39W3yb
    client-secret: Em_ND87BRg299Wzk_H00-Xf6uBqQLfYdBay8_xRwte_4s-V8dvKiUrlhIHVKZ0uF
    audience: https://dev-5ga4j08xhdasu7gq.us.auth0.com/api/v2/


logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus
