version: '3.9'
services:
  db-service4:
    image: 'postgres:latest'
    container_name: 'db-service4'
    environment:
      - 'POSTGRES_DB=db-payment'
      - 'POSTGRES_PASSWORD=payment'
      - 'POSTGRES_USER=payment'
    ports:
      - '5403:5432'
    networks:
      - red
  app-docker:
    container_name: 'container4-app'
    image: 'imageservice4-app:1.0.0.'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8003:8080'
    depends_on:
      - db-service4
    environment:
      - DATABASE_URL=jdbc:postgresql://db-service4:5432/db-payment
      - DATABASE_USERNAME=payment
      - DATABASE_PASSWORD=payment
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8070/eureka/
    networks:
      - red
networks:
  red:
    name: 'red'
