services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=db-booking-service'
      - 'POSTGRES_PASSWORD=micro2'
      - 'POSTGRES_USER=micro2'
    ports:
      - '5421:5432'
