version: '3.9'
services:
  db-service1:
    image: 'postgres:latest'
    container_name: 'db-service1'
    environment:
      - 'POSTGRES_DB=db-car-repo'
      - 'POSTGRES_PASSWORD=micro1'
      - 'POSTGRES_USER=micro1'
    ports:
      - '5400:5432'
    networks:
        - red
  app-docker:
    container_name: 'container1-app'
    image: 'imageservice1-app:1.0.0.'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8080'
    depends_on:
      - db-service1
    environment:
      - DATABASE_URL=jdbc:postgresql://db-service1:5432/db-car-repo
      - DATABASE_USERNAME=micro1
      - DATABASE_PASSWORD=micro1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8070/eureka/
    networks:
        - red
networks:
  red:
    name: 'red'